ProjectWeb/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|

*/
Route::resource('HomeLogin', 'HomeLoginController');
Route::resource('Customer', 'CustomerController');
Route::resource('Staff', 'StaffController');
Route::resource('Flight', 'FlightController');
Route::resource('Reserve', 'ReserveController');
Route::resource('Home', 'HomeController');
Route::resource('EditMyself', 'EditStaffController');
Route::resource('ChackFlightForCustomer', 'StaffCheckFilghtController');
Route::resource('ReserveForCustomerIndex', 'ReserveForCustomerController');
Route::get('/logout', 'AirlineUserControlle@logout');
Route::get('/logoutbackend', 'AirlineUserControlle@logoutbackend');
Route::post('', 'AirlineUserController@login');
Route::get('Login', function () {
  session_start();
  session_destroy();
      return view('Login.index');
});
Route::get('/HomeAdmin', function () {
    return view('Board');
});
Route::post('logincheck', 'AirlineUserController@login');
Route::post('logincheckCustomer', 'AirlineUserController@loginC');
Route::post('Edit', 'AirlineUserController@login');
Route::post('/CustomerUpdate', 'CustomerController@update');
Route::post('/StaffUpdate', 'StaffController@update');
Route::post('/StaffsUpdates', 'AirlineUserController@update');
Route::post('/FlightUpdate', 'FlightController@update');
Route::post('/CustomerHomeUpdate', 'HomeController@update');
Route::post('/addminsUpdate', 'AdminsController@update');
Route::get('/seatAirline', function () {
    return view('seatAirline');
});
Route::get('/customer', function () {
    return view('customer');
});
Route::get('/confrimSeat', function () {
    return view('confrirmSeat');
});
Route::get('/edit', function () {
    return view('Home.index');
});

//Route::get('/delete_data/{id}', 'HomeLoginController@destroy');
Route::post('/reserve/{id}', 'AirlineUserController@reserve');
///////////////////////////////////////////////////////////////////
Route::get('/BoardStaff', function () {
    return view('BoardStaff.BoardStaff');
});
Route::get('/masterStaff', function () {
    return view('BoardStaff.masterStaff');
});
// Route::get('/EditMyself', function () {
//     return view('BoardStaff.EditMyself.editStaffMyself');
// });

// Route::get('/ChackFlightForCustomer', function () {
//     return view('BoardStaff.ChackFlightForCustomer.ShowFlight');
// });

Route::get('/CreateFlightByStaff', function () {
    return view('BoardStaff.ChackFlightForCustomer.createFlight');
});

// Route::get('/ReserveForCustomerIndex', function () {
//     return view('BoardStaff.ReserveForCustomer.indexReserve');
// });

Route::get('/ReserveForCustomerCreate', function () {
    return view('BoardStaff.ReserveForCustomer.createReserve');
});

Route::get('/ReserveForCustomerEdit', function () {
    return view('BoardStaff.ReserveForCustomer.editReserve');
});

//////mild
Route::post('/showCustomerByStaff', 'InboardController@createReserve');

Route::post('/showTableFligthByStaff','InboardController@dataReserve');

Route::post('/ReserveForCustomerIndex','ReserveForCustomerController@reservestaff');
Route::resource('EditeMyselfAdmin', 'AdminsController');
/*Route::post('/InsertCustomer', 'AirlineUserController@InsertCustomer');
Route::get('/customer', 'AirlineUserController@Qcustomer');
Route::get('/customerdel/{cid}', 'AirlineUserController@Delcustomer');
Route::get('/Editecustomer/{cid}', 'AirlineUserController@Editecustomer');
Route::post('/Upcustomer', 'AirlineUserController@Upcustomer');


Route::post('/InsertStaff', 'AirlineUserController@InsertStaff');
Route::get('/staff', 'AirlineUserController@Qstaff');
Route::get('/staffdel/{cid}', 'AirlineUserController@Delstaff');
Route::get('/Editestaff/{cid}', 'AirlineUserController@Editestaff');
Route::post('/Upstaff', 'AirlineUserController@Upstaff');


Route::post('/InsertFlight', 'AirlineUserController@InsertFlight');
Route::get('/Flight', 'AirlineUserController@QFlight');
Route::get('/Flight/{fid}', 'AirlineUserController@DelFlight');
Route::get('/EditeFlight/{cid}', 'AirlineUserController@EditeFlight');
Route::post('/UpFlight', 'AirlineUserController@UpFlight');



Route::get('/index', function () {
    return view('home');
});
Route::get('/login', function () {
    return view('backend.LoginAdmin');
});
Route::get('/register', function () {
    return view('backend.Register');
});
Route::get('/Admin', function () {
    return view('backend.Board');
});
Route::get('/flight', function () {
    return view('backend.flight');
});
Route::get('/reserve', function () {
    return view('backend.reserve');
});
Route::get('/addcustomer', function () {
    return view('backend.addcustomer');
});

Route::get('/addstaff', function () {
    return view('backend.addstaff');
});

Route::get('/addflight', function () {
    return view('backend.addflight');
});
*/
?>

ProjectWeb/resources/views/Login/edit.blade.php
@extends('master')
@section('title','Staff')
@section('head')
@stop
@section('content')
<div id="content-wrapper">

	<div class="container-fluid">
		<!-- @if(count($errors)>0)
			<div class="aler alert-danger">
				<ul>
				@foreach($errors->all() as $error)
					<li>{{$error}}</li>
				@endforeach
				</ul>
			</div>
		@endif

		@if(\Session::has('success'))
			<div class="alert alert-success">
			<p>{{\Session::get('success')}}</p>
			</div>
		@endif-->
		<!-- Breadcrumbs-->
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="#">Dashboard</a>
			</li>
			<li class="breadcrumb-item active">Edit Profile</li>
		</ol>
		<div class="container mb-5">
			<a href="{{route('Staff.create')}}">
				<button type="submit" class="btn btn-primary">Edit Profile</button>
			</a>
			<h1 class="display-4 mt-5 mb-5">Admin</h1>
			<div class="row">
				<div class="form-row w-100">
					<div class="table-responsive">
						<table class="table table-hover">
							<tr>
								<th>First Name</th>
								<th>Last Name</th>
								<th>Sex</th>
								<th>Email</th>
								<th>Phone</th>
								<th>Position</th>
								<th></th>
								<th></th>
							</tr>
							@foreach($staff as $row)
							<tr>
								<td>{{$row['firstname']}}</td>
								<td>{{$row['lastname']}}</td>
								<td>{{$row['sex']}}</td>
								<td>{{$row['email']}}</td>
								<td>{{$row['phone']}}</td>
								<td>{{$row['position']}}</td>
								<td><a href="{{action('StaffController@edit',$row['sid'])}}" class="btn btn-primary">Edite</td>
								<td>
									<form method="post" class="delete_form" action="{{action('StaffController@destroy',$row['sid'])}}">
										{{ csrf_field() }}
									<input type="hidden" name="_method" value="DELETE"/>
									<button type="submit" class="btn btn-danger">Delete</button>
								</td>
							</tr>
							@endforeach
						</div>
					</div>
				</div>
			</div>
			<script type="text/javascript" src="{{ asset('bootstrap/js/bootstrap.min.js') }}"></script>
			<script type="text/javascript" src="{{ asset('bootstrap/js/bootstrap.bundle.js') }}"></script>

			<!-- Sticky Footer -->
			<footer class="sticky-footer">
				<div class="container my-auto">
					<div class="copyright text-center my-auto">
						<span>Welcom to Airline</span>
					</div>
				</div>
			</footer>
		</div>
		@stop
		@section('footer')
		@stop

ProjectWeb/resources/views/Login/index.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Login</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--===============================================================================================-->
  	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="css/util.css">
  	<link rel="stylesheet" type="text/css" href="css/main.css">
  <!--===============================================================================================-->
</head>
<body>
  <div class="limiter">
  		<div class="container-login100" style="background-image: url('images/bg-01.jpg');">
  			<div class="wrap-login100 p-t-30 p-b-50">
  				<span class="login100-form-title p-b-41">
  					Login
  				</span>
  				<form class="login100-form validate-form p-b-33 p-t-5"
          action="/logincheck" method="post">
            {{ csrf_field() }}
  					<div class="wrap-input100 validate-input" data-validate = "Enter username">
  						<input class="input100" type="text" name="username" placeholder="ID" >
  						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
  					</div>

  					<div class="wrap-input100 validate-input" data-validate="Enter password">
  						<input class="input100" type="password" name="pass" placeholder="Password">
  						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
  					</div>

  					<div class="container-login100-form-btn m-t-32">
  						<button class="login100-form-btn">
  							Login
  						</button>
  					</div>

  				</form>
  			</div>
  		</div>
  	</div>


  	<div id="dropDownSelect1"></div>

    <!--===============================================================================================-->
    	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    	<script src="vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    	<script src="vendor/bootstrap/js/popper.js"></script>
    	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    	<script src="vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    	<script src="vendor/daterangepicker/moment.min.js"></script>
    	<script src="vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    	<script src="vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    	<script src="js/main.js"></script>
</body>
</html>