ProjectWeb/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|

*/
Route::resource('HomeLogin', 'HomeLoginController');
Route::resource('Customer', 'CustomerController');
Route::resource('Staff', 'StaffController');
Route::resource('Flight', 'FlightController');
Route::resource('Reserve', 'ReserveController');
Route::resource('Home', 'HomeController');
Route::resource('EditMyself', 'EditStaffController');
Route::resource('ChackFlightForCustomer', 'StaffCheckFilghtController');
Route::resource('ReserveForCustomerIndex', 'ReserveForCustomerController');
Route::get('/logout', 'AirlineUserControlle@logout');
Route::get('/logoutbackend', 'AirlineUserControlle@logoutbackend');
Route::post('', 'AirlineUserController@login');
Route::get('Login', function () {
  session_start();
  session_destroy();
      return view('Login.index');
});
Route::get('/HomeAdmin', function () {
    return view('Board');
});
Route::post('logincheck', 'AirlineUserController@login');
Route::post('logincheckCustomer', 'AirlineUserController@loginC');
Route::post('Edit', 'AirlineUserController@login');
Route::post('/CustomerUpdate', 'CustomerController@update');
Route::post('/StaffUpdate', 'StaffController@update');
Route::post('/StaffsUpdates', 'AirlineUserController@update');
Route::post('/FlightUpdate', 'FlightController@update');
Route::post('/CustomerHomeUpdate', 'HomeController@update');
Route::post('/addminsUpdate', 'AdminsController@update');
Route::get('/seatAirline', function () {
    return view('seatAirline');
});
Route::get('/customer', function () {
    return view('customer');
});
Route::get('/confrimSeat', function () {
    return view('confrirmSeat');
});
Route::get('/edit', function () {
    return view('Home.index');
});

//Route::get('/delete_data/{id}', 'HomeLoginController@destroy');
Route::post('/reserve/{id}', 'AirlineUserController@reserve');
///////////////////////////////////////////////////////////////////
Route::get('/BoardStaff', function () {
    return view('BoardStaff.BoardStaff');
});
Route::get('/masterStaff', function () {
    return view('BoardStaff.masterStaff');
});
// Route::get('/EditMyself', function () {
//     return view('BoardStaff.EditMyself.editStaffMyself');
// });

// Route::get('/ChackFlightForCustomer', function () {
//     return view('BoardStaff.ChackFlightForCustomer.ShowFlight');
// });

Route::get('/CreateFlightByStaff', function () {
    return view('BoardStaff.ChackFlightForCustomer.createFlight');
});

// Route::get('/ReserveForCustomerIndex', function () {
//     return view('BoardStaff.ReserveForCustomer.indexReserve');
// });

Route::get('/ReserveForCustomerCreate', function () {
    return view('BoardStaff.ReserveForCustomer.createReserve');
});

Route::get('/ReserveForCustomerEdit', function () {
    return view('BoardStaff.ReserveForCustomer.editReserve');
});

//////mild
Route::post('/showCustomerByStaff', 'InboardController@createReserve');

Route::post('/showTableFligthByStaff','InboardController@dataReserve');

Route::post('/ReserveForCustomerIndex','ReserveForCustomerController@reservestaff');
Route::resource('EditeMyselfAdmin', 'AdminsController');
/*Route::post('/InsertCustomer', 'AirlineUserController@InsertCustomer');
Route::get('/customer', 'AirlineUserController@Qcustomer');
Route::get('/customerdel/{cid}', 'AirlineUserController@Delcustomer');
Route::get('/Editecustomer/{cid}', 'AirlineUserController@Editecustomer');
Route::post('/Upcustomer', 'AirlineUserController@Upcustomer');


Route::post('/InsertStaff', 'AirlineUserController@InsertStaff');
Route::get('/staff', 'AirlineUserController@Qstaff');
Route::get('/staffdel/{cid}', 'AirlineUserController@Delstaff');
Route::get('/Editestaff/{cid}', 'AirlineUserController@Editestaff');
Route::post('/Upstaff', 'AirlineUserController@Upstaff');


Route::post('/InsertFlight', 'AirlineUserController@InsertFlight');
Route::get('/Flight', 'AirlineUserController@QFlight');
Route::get('/Flight/{fid}', 'AirlineUserController@DelFlight');
Route::get('/EditeFlight/{cid}', 'AirlineUserController@EditeFlight');
Route::post('/UpFlight', 'AirlineUserController@UpFlight');



Route::get('/index', function () {
    return view('home');
});
Route::get('/login', function () {
    return view('backend.LoginAdmin');
});
Route::get('/register', function () {
    return view('backend.Register');
});
Route::get('/Admin', function () {
    return view('backend.Board');
});
Route::get('/flight', function () {
    return view('backend.flight');
});
Route::get('/reserve', function () {
    return view('backend.reserve');
});
Route::get('/addcustomer', function () {
    return view('backend.addcustomer');
});

Route::get('/addstaff', function () {
    return view('backend.addstaff');
});

Route::get('/addflight', function () {
    return view('backend.addflight');
});
*/
?>

ProjectWeb/app/reserve.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class reserve extends Model
{
    //
}

ProjectWeb/app/Http/Controllers/ReserveController.php
<?php

namespace App\Http\Controllers;
use DB;
use Illuminate\Http\Request;
use App\customer;
class ReserveController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      //$customers = customer::all()->toArray();
        session_start();
        if(!isset($_SESSION['account'])){
            return view('Login.index');
        }
        else{
          $data=DB::select('select * from
          reserves
          join customers on reserves.cid = customers.cid
          join flights on reserves.fid = flights.fid');
          return view('Reserve.index',compact('data'));
        //dd($data);
      }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      dd($id);
      session_start();
      if(!isset($_SESSION['account'])){
          return view('Login.index');
      }
      else{
        DB::table('reserves')->where('id',$id)->delete();
        return redirect()->route('Reserve.index')->with('success','ลบข้อมูลเรียบนร้อย');
      }
    }
}

ProjectWeb/resources/views/Reserve/create.blade.php
@extends('master')
@section('title','Add Customer')
@section('head')
@stop
@section('content')
<div id="content-wrapper">

	<div class="container-fluid">

		<!-- Breadcrumbs-->
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="#">Dashboard</a>
			</li>
			<li class="breadcrumb-item active">Customer</li>
		</ol>

<div class="container mt-5 mb-5">
	<h1 class="display-4 mt-5 mb-5">Add Customer</h1>
	<div class="row">
		<div class="col-lg-4">
		<!-- @if(count($errors)>0)
			<div class="aler alert-danger">
				<ul>
				@foreach($errors->all() as $error)
					<li>{{$error}}</li>
				@endforeach
				</ul>
			</div>
		@endif

		@if(\Session::has('success'))
			<div class="alert alert-success">
			<p>{{\Session::get('success')}}</p>
			</div>
		@endif-->
			<form action="{{url('Customer')}}" method="post" class="pt-5 pb-5">
				{{ csrf_field() }}
				<div class="form-group">
					<label for="idcard">ID Card</label>
					<input type="text" class="form-control" id="idcard" placeholder="ID Card" name="idcard">
				</div>
				<div class="form-group">
					<label for="password">Password</label>
					<input type="text" class="form-control" id="password" placeholder="Password" name="password">
				</div>
				<div class="form-group">
					<label for="fname">First Name</label>
					<input type="text" class="form-control" id="fname" placeholder="First Name" name="fname">
				</div>
				<div class="form-group">
					<label for="lname">Last Name</label>
					<input type="text" class="form-control" id="lname" placeholder="Last Name" name="lname">
				</div>
				<div class="form-group">
					<label for="Sex">Sex</label>
					<input type="text" class="form-control" id="Sex" placeholder="Sex" name="Sex">
				</div>
				<div class="form-group">
					<label for="Address">Address</label>
					<input type="text" class="form-control" id="Address" placeholder="Address" name="Address">
				</div>
				<div class="form-group">
					<label for="Email">Email</label>
					<input type="text" class="form-control" id="Email" placeholder="Email" name="Email">
				</div>
				<div class="form-group">
					<label for="phone">Phone</label>
					<input type="text" class="form-control" id="phone" placeholder="Phone" name="phone">
				</div>
				<button type="submit" class="btn btn-primary">  Add Customer  </button></a>
			</form>
		</div>
	</div>
</div>
</div>
@stop
@section('footer')
@stop

ProjectWeb/resources/views/Reserve/edit.blade.php
@extends("master")
@section("title","Edite Customer")
@section('head')
@stop
@section("content")
<div class="container mt-5 mb-5">
	<h1 class="display-4 mt-5 mb-5">Edite Profile</h1>
	<div class="row">
		<div class="col-lg-4">
			<form action="/CustomerUpdate" method="post" class="pt-5 pb-5">
				{{ csrf_field() }}
				<div class="form-group">
						<input type="hidden" class="form-control" id="id" placeholder="Enter id" name="id" value="<?= $customer[0]->cid; ?>">
					</div>
				<div class="form-group">
					<label for="idcard">ID Card</label>
					<input type="text" class="form-control" id="idcard" placeholder="ID Card" name="idcard"
					value="<?= $customer[0]->id_card; ?>">
				</div>
				<div class="form-group">
					<label for="password">Password</label>
					<input type="text" class="form-control" id="password" placeholder="Password" name="password" value="<?= $customer[0]->password; ?>">
				</div>
				<div class="form-group">
					<label for="fname">First Name</label>
					<input type="text" class="form-control" id="fname" placeholder="First Name" name="fname" value="<?= $customer[0]->firstname; ?>">
				</div>
				<div class="form-group">
					<label for="lname">Last Name</label>
					<input type="text" class="form-control" id="lname" placeholder="Last Name" name="lname" value="<?= $customer[0]->lastname; ?>">
				</div>
				<div class="form-group">
					<label for="Sex">Sex</label>
					<input type="text" class="form-control" id="Sex" placeholder="Sex" name="Sex" value="<?= $customer[0]->sex; ?>">
				</div>
				<div class="form-group">
					<label for="Address">Address</label>
					<input type="text" class="form-control" id="Address" placeholder="Address" name="Address" value="<?= $customer[0]->address; ?>">
				</div>
				<div class="form-group">
					<label for="Email">Email</label>
					<input type="text" class="form-control" id="Email" placeholder="Email" name="Email" value="<?= $customer[0]->email; ?>">
				</div>
				<div class="form-group">
					<label for="phone">Phone</label>
					<input type="text" class="form-control" id="phone" placeholder="Phone" name="phone" value="<?= $customer[0]->phone; ?>">
				</div>
				<div class="form-group">
					<!-- <input type="hidden" name="_method" value="PATCH"/> -->
					<button type="submit" class="btn btn-primary"> Update </button>
				</div>
			</form>
		</div>
	</div>
</div>
@stop
@section("footer")
@stop

ProjectWeb/resources/views/Reserve/index.blade.php
@extends('master')
@section('title','Reserve')
@section('head')
@stop
@section('content')
<div id="content-wrapper">

	<div class="container-fluid">
		<!-- @if(count($errors)>0)
			<div class="aler alert-danger">
				<ul>
				@foreach($errors->all() as $error)
					<li>{{$error}}</li>
				@endforeach
				</ul>
			</div>
		@endif

		@if(\Session::has('success'))
			<div class="alert alert-success">
			<p>{{\Session::get('success')}}</p>
			</div>
		@endif-->
		<!-- Breadcrumbs-->
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="#">Dashboard</a>
			</li>
			<li class="breadcrumb-item active">Reserve</li>
		</ol>
		@if(count($errors)>0)
			<div class="aler alert-danger">
				<ul>
				@foreach($errors->all() as $error)
					<li>{{$error}}</li>
				@endforeach
				</ul>
			</div>
		@endif
		<div class="container mb-5">
			<!-- <a href="{{route('Customer.create')}}" class="btn btn-primary">Add Customer</a> -->
			<h1 class="display-4 mt-5 mb-5">Reserve</h1>
			<div class="row">
				<div class="form-row w-100">
					<div class="table-responsive">
						<table class="table table-hover">
							<tr>
								<th>ID User</th>
								<th>Plane</th>
								<th>Source</th>
								<th>Destinetion</th>
								<th>Seat</th>
								<th>Depart</th>
								<th>Return</th>
								<th>Price</th>
								<th></th>
								<th></th>
							</tr>
							@foreach ($data as $row)
							<tr>
								<td>{{($row->id_card)}}</td>
								<td>{{($row->planename)}}</td>
								<td>{{($row->source)}}</td>
								<td>{{($row->destinetion)}}</td>
								<td>{{($row->seat)}}</td>
								<td>{{($row->startDate)}}</td>
								<td>{{($row->endDate)}}</td>
								<td>{{($row->price)}}</td>
						
							</tr>
							@endforeach
						</table>
					</tbody>
				</div>
			</div>
		</div>
	</div>
			<script type="text/javascript" src="{{ asset('bootstrap/js/bootstrap.min.js') }}"></script>
			<script type="text/javascript" src="{{ asset('bootstrap/js/bootstrap.bundle.js') }}"></script>

			<footer class="sticky-footer">
				<div class="container my-auto">
					<div class="copyright text-center my-auto">
						<span>Welcom to Airline</span>
					</div>
				</div>
			</footer>

		</div>
		@stop
		@section('footer')
		@stop